// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Cart struct {
	ID        int32        `json:"id"`
	UserID    int64        `json:"user_id"`
	ProductID int64        `json:"product_id"`
	Quantity  int32        `json:"quantity"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Feed struct {
	ID        int32        `json:"id"`
	UserID    int64        `json:"user_id"`
	Title     string       `json:"title"`
	Caption   string       `json:"caption"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Product struct {
	ID          int32          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Volume      string         `json:"volume"`
	Unit        string         `json:"unit"`
	Stock       int32          `json:"stock"`
	Sold        int32          `json:"sold"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type User struct {
	ID        int32          `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	UserType  string         `json:"user_type"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
